# Важно, у всех nodes должны быть одинаковые cookie https://www.rabbitmq.com/clustering.html#erlang-cookie

version: '3.9'
services:
  rabbitmq1:
    image: rabbitmq:3.12-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=${RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS}
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./data/rabbitmq1:/var/lib/rabbitmq/mnesia" # сохраняем стейт - при ошибке, контейнер перезагрузится и не потеряет данные
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    restart: always


  rabbitmq2:
    image: rabbitmq:3.12-management
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=${RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS}
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./data/rabbitmq2:/var/lib/rabbitmq/mnesia" # сохраняем стейт - при ошибке, контейнер перезагрузится и не потеряет данные
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    restart: always


  rabbitmq3:
    image: rabbitmq:3.12-management
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=${RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS}
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./data/rabbitmq3:/var/lib/rabbitmq/mnesia" # сохраняем стейт - при ошибке, контейнер перезагрузится и не потеряет данные
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    restart: always

  haproxy:
    image: haproxy:2.8
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - "15672:15672"
      - "5672:5672"